[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paxy"
version = "0.1.0"
description = "Paxy: a BASIC-like language that compiles to Python bytecode (.pyc)."
authors = [
  { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"

# This is the magic that makes the `paxy` command
[project.scripts]
paxy = "paxy.cli:main"

[tool.setuptools.packages.find]
where = ["."]