# minimal local stubs for 'bytecode' to satisfy mypy
from typing import Any, Mapping, Optional

class Label: ...
class CellVar: ...
class FreeVar: ...

class Instr:
    name: str
    arg: Any
    lineno: int
    def __init__(
        self, name: str, arg: Any | None = ..., *, lineno: int | None = ...
    ) -> None: ...

# Lightweight stand-ins for the enums you coerce to:
class BinaryOp: ...
class Compare: ...

# You read this (VALID_OPS = set(dis.opmap)), type as Mapping is enough
opmap: Mapping[str, int]
