# stubs/importlib/_bootstrap_external.pyi
from typing import Optional
from types import CodeType

def _code_to_timestamp_pyc(code: CodeType, mtime: int, size: int) -> bytes: ...
def _code_to_hash_pyc(code: CodeType, checked_hash: Optional[bytes]) -> bytes: ...
def _write_atomic(path: str, data: bytes, *, mode: int = ...) -> None: ...
